### ISSUE TITLE
How do I get it working on Windows?

### ISSUE THREAD

**Issue by sxyCode** [rckclmbr/pyportify#10]
Hi, I'd like to use your tool, but I can't get it working on windows (8.1)
Is it possible? And if so, could you provide a guide to make it work?

Thanks in advance!

**Comment by rckclmbr** [comment]
The total bummer is that windows isn't supported :(  The good news is I'm working on https://github.com/rckclmbr/goportify which will support windows as soon as I can get the build working :)

**Comment by ensign-rbaker** [comment]
@sxyCode, you can spin up a VM with Ubuntu on it and get it working that way. I'm doing it as we speak and it works great. If you don't know how, just do some googling and you should be able to get the help you need.

**Comment by jakestevens96** [comment]
Hi, is there an update on the Windows version yet? I'm going to be doing it in a Virtual Machine but I was just wondering for further down the line.

**Comment by rckclmbr** [comment]
Unfortunately not.  For Windows support I will definitely need to move away from libspotify (it's deprecated anyway), and move to the Web API. I think it could easily be built into static binary then.  I haven't had any time to do this, but someone else can pick it up I don't think it would be too much work.

**Comment by jordam** [comment]
I've tackled a simplified windows version over here https://github.com/jordam/ezportify

**Comment by rckclmbr** [comment]
I've added Windows support.  See the "Windows" section in the README
