### ISSUE TITLE
Google.py - KeyError: 'id' copy_all returned -1

### ISSUE THREAD

**Issue by shan3k** [rckclmbr/pyportify#101]

**Comment by rckclmbr** [comment]
Could you make a public playlist with these tracks, and send it to me?

**Comment by shan3k** [comment]
@rckclmbr I can't unfortunately but I will recreate the issue with a public playlist if possible and update.

**Comment by rckclmbr** [comment]
This should be fixed in v0.3.14, give it a try and let me know.
