### ISSUE TITLE
Login Failed - Google Account

### ISSUE THREAD

**Issue by gabernardone** [rckclmbr/pyportify#120]
I'm getting login error in my google account. The user and password are correct, I have no verification in 2 steps and I have disabled the captcha. What could be happening?

**Comment by Zerqz** [comment]
I made a "app password" for my google account, and used that. Then everything worked fine.

**Comment by iaejean** [comment]
@Zerqz , how do you do that?

**Comment by Zerqz** [comment]
[Like this](https://security.google.com/settings/security/apppasswords)

**Comment by iaejean** [comment]
@Zerqz Thanks i had to edit my account to 2 step auth to be able to add a app password, it works

**Comment by JohnTheodore** [comment]
Why doesn't it use oauth2 instead of needing a username/password? I have 2FA on, but oauth2 would solve all these auth issues.
