### ISSUE TITLE
pyportify.exe blocked by Traps Endpoint Protection

### ISSUE THREAD

**Issue by talllguy** [rckclmbr/pyportify#122]
The _Palo Alto Networks_ **Traps** EP software is blocking _pyportify.exe_. Possibly related to https://github.com/rckclmbr/pyportify/issues/106#issuecomment-305553695

Here are the prevention details. 

### Application information:
Process ID:	13908
Application location:	{tempdir}\pyportify.exe
Command line:	"{tempdir}\pyportify.exe" 
File origin:	Hard drive on this computer
User name:	{redacted}

### Prevention information:
Prevention date:	Monday, November 6, 2017
Prevention time:	18:19:50 PM
OS version:	6.2.9200.2.0.0.256.1
Component:	WildFire
Traps code:	c0400055
Prevention description:	Suspicious executable detected
Additional information 1:	{tempdir}\pyportify.exe
Additional information 2:	8C2B8893F8E9C05B7F812BBA94A4854F7904F400744E44B279D2C0181070C54F
Additional information 3:	8C2B8893F8E9C05B7F812BBA94A4854F7904F400744E44B279D2C0181070C54F
Additional information 4:	1

**Comment by rckclmbr** [comment]
Definitely related -- pyinstaller apps gets flagged as a trojan on some AV.  Unless there actually is a trojan with pyinstaller, this can be ignored.

To get confirmation, you can build from source and verify yourself it's still flagged.

I'm going to close this for this sake of keeping the other one open.
