### ISSUE TITLE
auth fails

### ISSUE THREAD

**Issue by JohnTheodore** [rckclmbr/pyportify#126]
I believe since I'm using u2f, I'm not able to make 'app passwords'.

It'd be great if the tool just used oauth2, then you don't need less secure app passwords, and you can scope the token to be able to only modify google play which is a lot more secure to only give least privilege access.

**Comment by rckclmbr** [comment]
Unless something has changed recently, none of the Google music apis use
oauth.

**Comment by JohnTheodore** [comment]
You're right.. so weird. I expected all of the google services to use oauth2, huh. There is no official api either.
