### ISSUE TITLE
Doesn't finish/Progress screen shows nothing.

### ISSUE THREAD

**Issue by darthjoey91** [rckclmbr/pyportify#13]
I've gotten pyportify to copy playlists with expected results of not everything matching and some false positives, but otherwise pretty good.

The problem comes when it's done transferring, it just stops. It has made the playlists correctly, but there's no way to continue or exit gracefully. I have to Ctrl+C in the terminal to stop it.

Similarly, the progress screen shows the same thing all the time. Just a blank album cover and an empty progress bar.

**Comment by rckclmbr** [comment]
This is because the socket.io endpoints for the progress isn't implemented.  Should be easy to do.
