### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by Que20** [rckclmbr/pyportify#16]
So I'm trying to install Pyportify and here is my error when launching "pip install pyportify" : 
`Command "python setup.py egg_info" failed with error code 1 in` `/private/var/folders/bt/9s1dt305393cgxtfzylb05qh0000gn/T/pip-build-3TbVod/pyspotify`

Here is the full log : http://pastebin.com/sR7mhjqv

Can someone help me on this ?
Thanks.

**Comment by rckclmbr** [comment]
You need libffi installed.  What OS is this, looks like OS X?

Try this:

```
brew install libffi
```

**Comment by Que20** [comment]
Yeah!
$ brew install pkg-config libffi
$ export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig/
Thanks :)

**Comment by magichim** [comment]
what is libffi?... i'm also same situation.
