### ISSUE TITLE
Break apart playlists of > 1000 songs

### ISSUE THREAD

**Issue by rckclmbr** [rckclmbr/pyportify#18]
GM only allows playlists to have 1000 songs

**Comment by Suero** [comment]
Everyone should give feedback to Google about increasing this limit, you can do this by going to the Play Music webpage, press the cog in the top right corner and "Help & Feedback" -> "Send Feedback".

**Comment by d0tfil3** [comment]
Hello, i have that issue too, even one year later. What about dividing large playlists into small (x1000 songs)? It would be awesome.

**Comment by rckclmbr** [comment]
Welp, finally got this done.  v0.3.14 breaks them apart into groups of 1000
