### ISSUE TITLE
Installing and running on a Mac

### ISSUE THREAD

**Issue by DrWig** [rckclmbr/pyportify#20]
I couldn't get pyportify running on a Mac UNLESS I installed python using homebrew and installed cffi.  Installing Python using the packages from the python web page caused various errors in the installing of pyportify.

I think the steps were:

1. install homebrew:
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

2. install python:
$ brew install python

3. Workaround on OSX (see https://pyspotify.mopidy.com/en/latest/installation/)
$ sudo ln -s /usr/local/opt/libspotify/lib/libspotify.12.1.51.dylib \
/usr/local/opt/libspotify/lib/libspotify

4. Install libffi and cffi (not sure if both, or just cffi are needed)
$ brew install pkg-config libffi
$ export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig/ # May change with libffi version
$ pip install cffi

5. Install pyportify
$ pip install pyportify

**Comment by miikkij** [comment]
Thank you so much!

**Comment by marianolatorre** [comment]
uff I wished I saw this before a thousand other blog posts, thanks!

**Comment by rckclmbr** [comment]
Made installation sooo much easier, this should be resolved.
