### ISSUE TITLE
Cannot install on arch linux (error code 1)

### ISSUE THREAD

**Issue by yurilebbie** [rckclmbr/pyportify#21]
Quickly fails after the sudo pip install pyportify command
have tried with python2 and python3

Here is the output:
[yurilebbie@comp pyportify]$ sudo pip install pyportify
Collecting pyportify
  Using cached pyportify-0.2.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-geymkjax/pyportify

**Comment by rckclmbr** [comment]
Not sure what you're doing differently, but this works for me on arch:

```
sudo pacman -S python2 python2-pip python2-cffi base-devel
curl -LO "https://aur.archlinux.org/packages/li/libspotify/libspotify.tar.gz"
tar -xzf libspotify.tar.gz
cd libspotify
makepkg -s
sudo pacman -U *.tar.xz
sudo pip2 install pyportify
```

**Comment by yurilebbie** [comment]
I was using pip instead of pip2, using the proper one solved this for me
