### ISSUE TITLE
one playlist gets a 500 return

### ISSUE THREAD

**Issue by jflynnSMG** [rckclmbr/pyportify#24]
I have an 80s playlist, because I'm awesome like that, however it will not transfer.
![image](https://cloud.githubusercontent.com/assets/9932557/7141585/3db7f388-e298-11e4-95b2-aefc20ae7e8b.png)
I have renamed it in spotify and made it public, but no luck.  Any suggestions?

**Comment by rckclmbr** [comment]
Is the playlist public, and could you send me a link?  So I can test it, but also because the 80s are awesome.

**Comment by jflynnSMG** [comment]
http://open.spotify.com/user/nerdlifestyle/playlist/3nuTXQqMFljYVzpcqp7XRn

Is the list.  I duplicated it and it ported over.

**Comment by rckclmbr** [comment]
I think this is actually an error at spotify -- the timeout was masking another error:  ```spotify.error.LibError: General permanent error```

But it was only one specific track -- "Joey Scarbury - Theme From "Greatest American Hero" (Believe It Or Not)".

I changed pyportify to skip past tracks where spotify has a problem loading.  I released a new version of this, could you try it out and let me know if it works?

Run this to upgrade:

```sudo pip install --upgrade pyportify```

**Comment by jflynnSMG** [comment]
Works great, although I'm not sure if I want to live in a world without Believe It Or Not.

If I can make a feature request, I've noticed that the majority of tracks that don't port over well contain "- 'year' remaster"
![image](https://cloud.githubusercontent.com/assets/9932557/7159245/6a06f2e6-e346-11e4-928a-66f410d6ee65.png)

Would it be possible to do some kind of regex check to prep the string before it goes to Google?  I'm already ported over, but it might be helpful in the future.  Thanks for fixing this for me.
