### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LucasDachman** [rckclmbr/pyportify#26]
I get this error when running `pyportify`

i'm running ubuntu 14.04.2 64-bit on a virtual machine.

any ideas?

**Comment by rckclmbr** [comment]
There was someone else who ran into this same problem.  They fix was to remove spotify_appkey.key and reinstall it.  No idea why it's happening though.  See https://github.com/rckclmbr/pyportify/issues/3 or:

1.  Remove /usr/lib/python2.7/site-packages/pyportify/spotify_appkey.key
2.  `sudo pip uninstall pyportify`
3.  `sudo pip install pyportify`

**Comment by LucasDachman** [comment]
figured it out, thanks
