### ISSUE TITLE
Segfault when logging into Google on Fedora

### ISSUE THREAD

**Issue by squizzi** [rckclmbr/pyportify#3]
I installed on Fedora using these instructions:

```bash 
sudo rpm -ivh http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(grep -o [0-9]* /etc/fedora-release).noarch.rpm
sudo yum update
sudo yum -y install python-pip python-devel libffi-devel libspotify-devel
sudo pip install pyportify
```
But that was short-lived, I get segfaults when trying to login to my Google account. I can't get much info from it since I can't get debuginfo for libspotify but it seems to be the culprit:

```bash
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdbfff700 (LWP 29590)]
0x00007fffb5a0db9e in ?? () from /lib64/libspotify.so.12
```
I thought that maybe the libspotify provided by rpmfusion non-free is out of date/different then the one from the spotify site.

```bash
$ rpm -qa | grep libspotify
libspotify-12.1.51-4.fc21.x86_64
libspotify-devel-12.1.51-4.fc21.x86_64
```

So I grabbed the libspotify from here: https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz and made sure that we were loading the correct library and I still get a segfault.  

I thought maybe the issue was 2-Factor Auth on Google but I setup an auth password and still encountered the segfault.  

I'm not too good at troubleshooting python but will be happy to help.

**Comment by rckclmbr** [comment]
Can you get a core dump?  See http://jodal.no/post/5779178001/log-from-the-debugging-of-a-segfault/ for how to get one.

Also, if you run ```pyportify-copyall```, does it segfault immediately?

**Comment by rckclmbr** [comment]
I was reading https://github.com/mopidy/pyspotify/issues/150 and you may have run into this.  Can you copy spotify_appkey.key (so we can send it to them if it actually is the problem), uninstall pyportify (```pip uninstall pyportify```) and install it again?

**Comment by heroheman** [comment]
Not Linux related, had the same on osx
http://zeug.florenz.io/RNDwY.png

Reinstalling did not help.

**Comment by squizzi** [comment]
Yep, that's the problem, it's the ```spotify_appkey.key```.  I moved it and reinstalled pyportify and it's working now.  I can get you a core file in a little while, its going to take a bit to upload.

Problem is I can't login with spotify creds now, and that's most likely because I don't have premium anymore.

Weirdest part of it all, the appkey is actually identical when diffing them: 

```
# diff ./home/ksquizza/spotify_appkey.key ./usr/lib/python2.7/site-packages/pyportify/spotify_appkey.key 
<nothing> 
# md5sum ./usr/lib/python2.7/site-packages/pyportify/spotify_appkey.key ./home/ksquizza/spotify_appkey.key 
7851bafa64c4aeadf2d718760f85b0b3  ./usr/lib/python2.7/site-packages/pyportify/spotify_appkey.key
7851bafa64c4aeadf2d718760f85b0b3  ./home/ksquizza/spotify_appkey.key
```

**Comment by leadfeet123** [comment]
Getting the same error, what was the solution again. I tried removing spotify_appkey.key and uninstalling and reinstalling pyportify to no avail
