### ISSUE TITLE
Spotify Auth fail

### ISSUE THREAD

**Issue by Poag** [rckclmbr/pyportify#37]
Having an issue logging in with my Spotify account. Reporting bad username/password.

Have logged into my Spot account to check the passwd, changed it to be doubly sure. Still fails.

Using both the cli and web versions. Updated using pip. Running ubuntu

**Comment by rckclmbr** [comment]
Yep, it will deny auth if you dont have spotify premium.  I know the feelings -- I have to resubscribe every time I need to fix a bug :(

**Comment by Poag** [comment]
Out of interest, why does it require the Spot Premium? I can browse my spot playlists without prem and get the track names?

**Comment by rckclmbr** [comment]
It's a requirement of a dependency, libspotify, which is used to make third-party music apps (it supports music streaming).  I'd like to get rid of that dependency, but other solutions have been really problematic, because any web calls have a dependency on a swf.
