### ISSUE TITLE
Seg Fault - Might be Linux related?

### ISSUE THREAD

**Issue by darthjoey91** [rckclmbr/pyportify#4]
I keep getting a seg fault when I try to log into Google using an app password. I have not tried turning off two-factor.

I also get a seg-fault when just trying the copyall version of the command, before I can log in.

Running Linux Mint 17.1.

**Comment by rckclmbr** [comment]
Possibly related to #3

**Comment by rckclmbr** [comment]
Definitely duplicate of #3, I'll close this as the other has more information
