### ISSUE TITLE
Error starting pyportify: ImportError

### ISSUE THREAD

**Issue by craigcabrey** [rckclmbr/pyportify#44]
Running Arch Linux, installed pyportify via `pip2`. I'm getting an error while trying to start pyportify:

```python
Traceback (most recent call last):
  File "/usr/bin/pyportify", line 9, in <module>
    load_entry_point('pyportify==0.2.6', 'console_scripts', 'pyportify')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pyportify/server.py", line 5, in <module>
    from pyportify.views import app as application
  File "/usr/lib/python2.7/site-packages/pyportify/views.py", line 10, in <module>
    from socketio import socketio_manage
ImportError: cannot import name socketio_manage
Exception KeyError: KeyError(139902830899600,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

I traced this down to [this](http://stackoverflow.com/a/12639040) StackOverflow post, but it doesn't seem to resolve the issue.

I tried moving the `import` statement after the monkey patching:

```python
import os
import sys

import gevent
from gevent import monkey
monkey.patch_all()
import threading
```

I also tried removing the `threading` module from the current imports before monkey patching, followed by reloading after monkey patching.

```python
import os
import sys
if 'threading' in sys.modules:
    del sys.modules['threading']

import gevent
from gevent import monkey
monkey.patch_all()
import threading
```

Can you shed any light on this? Thanks!

**Comment by rckclmbr** [comment]
Can you try `pip install gevent-socketio` and let me know if that fixes it
for youb (from another thread)

**Comment by zero6699** [comment]
This helped me with my problem.  I have tried about 3 separate ubuntu installs (14.04 14.10 and 15.10) and none of them worked.  I did try to install socketio though other ways but none of them worked. Maybe you should include that in the guide.  Thanks for the help.

**Comment by craigcabrey** [comment]
@rckclmbr Installing `gevent-socketio` fixed the issue. Can you add it as a requirement to `requirements.txt`?
