### ISSUE TITLE
SSL Error from requests module

### ISSUE THREAD

**Issue by wbh1** [rckclmbr/pyportify#53]
SSL error caused by Requests because of an untrusted certificate when logging into Google. Stems from gpsoauth package. Specifically, the __init__.py file. I was able to solve this by manually modifying a function in the file. See below:

def _perform_auth_request(data):
    res = requests.post(auth_url, data,
                        headers={'User-Agent': useragent}, verify=False)

    return google.parse_auth_response(res.text)

Adding the 'verify=False' removes the verification step for the SSL cert, which is super insecure but was by far the easiest workaround I could think of. 

Is there a way that we can fix this going forward to disable verification if an SSL error is thrown because of an untrusted cert?

**Comment by rckclmbr** [comment]
We definitely don't want to disable ssl verification for untrusted certs.  The real question is why was it untrusted for you?  If you visit https://android.clients.google.com/ in your browser, you can clearly see it's a valid certificate.

The only thing that stands out is that maybe you have an older version of ssl, as certifi (and probably requests) says they replaced their old 1024-bit keys with strong 2048-bit, but that older versions of openssl don't validate the stronger keys.

Could you let me know the output of the following:

```
openssl version
python -c "import certifi; print certifi.__version__"
python -c "import gpsoauth; print gpsoauth.__version__"
python -c "import requests; print requests.__version__"
```

or even better, the output of `pip freeze`

also, whether or not this throws an exception:

```
python -c "import requests; requests.get('https://android.clients.google.com/auth')"
```

**Comment by flaminc** [comment]
I get the same error from you docker image and when doing a fresh docker build from your git repo.

**Comment by wbh1** [comment]
Hi. Let me preface this with also saying that I experienced these issues on 2 separate computers. I installed the latest 15.10 Ubuntu build on my work machine in a VM and that didn't work, so I figured I'd toy more with it when I got to my home computer. (Note: I also tried running pyportify from a live boot of 15.10 for kicks, but it didn't work either). I booted my home computer to Ubuntu 15.04 and had the same issues.

Anyway, here's the outputs.

`OpenSSL version is OpenSSL 1.0.1f 6 Jan 2014`

pip freeze output: 
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
    req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 299, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError

Storing debug log for failure in /tmp/tmpP6BJ5L
```
next:
```
python -c "import certifi; print certifi.__version__"
2015.11.20.1
```
next:
```
python -c "import gpsoauth; print gpsoauth.__version__"
0.0.5
```
next:
```
python -c "import requests; print requests.__version__"
2.4.3
```
Lastly:
```
python -c "import requests; requests.get('https://android.clients.google.com/auth')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError
```

**Comment by rckclmbr** [comment]
This is a problem with certifi and openssl 1.0.1f.  They recently upgraded to 2048-bit root certificates.  I'll look into a fix as soon as I can (sorry, things have been really busy at work), but try using an older version of certifi

**Comment by brandonhall** [comment]
Thanks for the solution @flaminc - one command and done

**Comment by CWSpear** [comment]
@flaminc's solution worked for me, too.

Is this not an appropriate permanent solution?

@rckclmbr Is there a way we can update the `Dockerfile` to export that or at least add the `env` flag to the `README`?

**Comment by sykosoft** [comment]
docker run -e "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt" -t -i --rm rckclmbr/pyportify /ve/bin/pyportify-copyall

**Comment by rckclmbr** [comment]
Should be fixed in latest version
