### ISSUE TITLE
Issue running PyPortify - Just Installed it

### ISSUE THREAD

**Issue by robromanowski** [rckclmbr/pyportify#58]
I'll preface by saying I'm a beginner when it comes to Linux enivronments, I only have some experience in using simple tasks in Ubuntu, eOS, and RHEL.

I am running Ubuntu 15.1 in VMWare Player.

I followed the instructions, I don't think I Got any errors. 

Now when I go to actually run it:
pyportify

I get this error:

> robert@ubuntu:~$ pyportify
> Traceback (most recent call last):
>   File "/usr/local/bin/pyportify", line 9, in <module>
>     load_entry_point('pyportify==0.2.9', 'console_scripts', 'pyportify')()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
>     return self.resolve()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python2.7/dist-packages/pyportify/server.py", line 5, in <module>
>     from pyportify.views import app as application
>   File "/usr/local/lib/python2.7/dist-packages/pyportify/views.py", line 10, in <module>
>     from socketio import socketio_manage
> ImportError: cannot import name socketio_manage
> Exception KeyError: KeyError(139845106397264,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

I tried googling. Found 1 thread about pip socketio - I tried that and still the same error when I tried to run pyportify again.

Any ideas what I'm doing wrong

**Comment by ssa3512** [comment]
Just ran into this as well. Looks like there is a fix in issue #47. Downgrade SocketIO with the command "sudo pip install -Iv Flask-SocketIO==0.5.0" This fixed the issue for me.

**Comment by rckclmbr** [comment]
This should be fixed, try the latest.  The binary will probably work best.
