### ISSUE TITLE
Spotify Premium account needed

### ISSUE THREAD

**Issue by voyager** [rckclmbr/pyportify#59]
I used to have Spotify premium account for some time, but now I don't anymore.
I've spend the whole day yesterday and part of today in making pyportify work, and today I've succeeded, only to hit the last obstacle as I don't have Premium account anymore.

Why exactly the Premium account is needed?

**Comment by zero6699** [comment]
So the Premium account is needed, I think to access the API.  But...
1. Make sure all of your playlists are shared,
2. Make a new account with a different email account.
3. Opt in to the free 10 day trial.
4. Become friends with your old account 
5. Cancel your free trial.
6. Profit?

**Comment by jordam** [comment]
pyportify uses libspotify. Libspotify is an official spotify library and creates this limitation.

They have a new web based api out there that doesn't require a premium account but it still needs to be integrated into pyportify.

I've managed to get this working by using copy_all.py as a springboard, but I wasnt able to get a lot of the library working so I've put out a stripped down windows focused version over at [ezportify](https://github.com/jordam/ezportify).

With a bit of elbow grease I'm sure the web api code can be backported over here.

**Comment by rckclmbr** [comment]
jordam, may as well contribute the code here! I've been considering getting
away from pyspotify, but have been hesitant due to the user having to get
their own api key. However I think it would make up for it, because
installation is such a pain in the ass (due to dependent c lib)

**Comment by jordam** [comment]
Feel free to port any of it in, but if you look at the source code you'll start to get an idea of why I didn't try to push any of it over lol.

I've stripped everything down to the console interface of copy_all, copied over the google.py library and modified it to work in windows, then coded the spotify web api interface inline with the main routine. Initial development speed was the primary focus.

I've also bypassed the api key requirement, just check out the project ;)

**Comment by voyager** [comment]
Thanks @zero6699, I wish it was that easy. I come from an unsupported country and my premium was some Telia-Sonera promotion that lasted 4-5 months. I can open another free account, however, I cannot start the premium trial, due to payment limitations imposed by the region of my CC issuer and PP account.

I will give a shot to your project @jordam, thanks! :)

**Comment by voyager** [comment]
@jordam, EZPortify worked like a charm! Thanks! :)

**Comment by rckclmbr** [comment]
@jordam thanks for the pointers, added support for Windows with your help.

**Comment by jordam** [comment]
@rckclmbr Awesome, any thoughts on the premium bypass?

**Comment by rckclmbr** [comment]
@jordam how do you mean? premium bypass should work fine, you just won't be able to see any collaborated or private playlists -- so like you said, just make them all public.

**Comment by jordam** [comment]
@rckclmbr Sorry, that was a bit of a sparse comment looking back on it.
The secondary account method wouldn't have worked for the original poster as the spotify process works differently in his home country. Moving off of libspotify is advised by spotify as they no longer guarantee functionality going forward.
