### ISSUE TITLE
Incompatible with 2-factor authentication

### ISSUE THREAD

**Issue by magdalar** [rckclmbr/pyportify#6]
This appears to not work if you require 2-factor authentication for your Google account. I suspect the same may be true of the Spotify login (e.g. Facebook 2-factor).

**Comment by edanc** [comment]
I had issues with it as well. I just took it off and made sure my google account had ` access for less secure apps has been enabled`

**Comment by rckclmbr** [comment]
You don't need to disable 2-factor in google.  You can use [app passwords](https://support.google.com/accounts/answer/185833?hl=en) to create a (temporary) password.  You can then delete the password after you've finished.

For Spotify, you can have a "spotify" password while still being connected to Facebook (and thus, not using Facebook's 2FA).  Just [reset your password](https://www.spotify.com/us/password-reset/) if you haven't already set one.
