### ISSUE TITLE
Insufficient client scope error when copying "Saved Tracks"

### ISSUE THREAD

**Issue by joselitojunior1** [rckclmbr/pyportify#60]
After selecting all the playlists that I want to import to Google Play Music, I'm get this error on terminal, and it stays stucked in there:

```
File "/usr/local/lib/python3.5/site-packages/pyportify/spotify.py", line 122, in _http_get
    raise Exception("Error: {0}, url: {1}".format(data, url))
Exception: Error: {'error': {'message': 'Insufficient client scope', 'status': 403}}, url: https://api.spotify.com/v1/me/tracks
```

**Comment by rckclmbr** [comment]
Did you select the proper permissions when retrieving the oauth token?  Also, do you have spotify premium?  I'm not entirely sure how it will function if you aren't a premium user.

**Comment by joselitojunior1** [comment]
yep, i've select the right permissions and have spotify premium. It lists all my playlists and let me choose what is the ones I want to import, but when it actually starts importing, it breaks and the console output the error

**Comment by jordam** [comment]
Do any of them import?

Its very odd that it would show your playlists but it would be unable to pull the tracks from them.

**Comment by joselitojunior1** [comment]
Nop, it breaks exactly when it starts importing. The console keeps clean before this point.

**Comment by jordam** [comment]
I might have an inkling of whats going on. The url used for oauth isnt requesting the proper permissions for what pyportify wants to do.

When you go to get an oauth token be sure to check all the checkboxes regardless of what the oauth page says. That might get you where you need to be.

If that's still not working do you think you could give this in-browser version a shot?
https://github.com/jordam/portify.js

It should do pretty much all the steps for you and works on non-premium meaning if your still running into problems something might be truly wrong with your spotify account.

**Comment by pjssilva** [comment]
I get this error only when I am trying to copy "Saved Tracks". The other playlists (that are not too big) can be copied  but Saved Tracks no. 

I tried to use the above portify.js but when trying to create a bookmark I get an error.

**Comment by rckclmbr** [comment]
This has actually been resolved in the repo itself.  You're correct -- there was no throttling to the service. I haven't made a release with this fix yet (at least for Windows).  Are you on OSX?  If so, you can give https://github.com/rckclmbr/pyportify/releases/download/v0.3.4/pyportify.dmg a try.

**Comment by rckclmbr** [comment]
> I get this error only when I am trying to copy "Saved Tracks"

This might be the problem, I'll check it out.

**Comment by LarsOL** [comment]
Can confirm ticking everything works.
This "https://developer.spotify.com/web-api/using-scopes/" seems to imply you need 'user-library-read' permission for saved tracks
Quote:
user-library-read	Read access to a user's "Your Music" library.	"Access your saved tracks and albums"

**Comment by superslimjimmy** [comment]
Need to change the URL to be [https://developer.spotify.com/web-api/console/get-playlists/](https://developer.spotify.com/web-api/console/get-playlists/)

**Comment by Timofcourse** [comment]
I also ran into this error, but I can confirm @LarsOL suggestion of adding "user-library-read" does in fact fix it. Thanks!

**Comment by willw00** [comment]
Thanks for the suggestion @LarsOL.  Worked for me too!
