### ISSUE TITLE
Large playlist requests aren't being throttled

### ISSUE THREAD

**Issue by LovedByTheLord** [rckclmbr/pyportify#62]
I have several playlists in Spotify that I'm trying to move over to Google with pyportify.  Most of my playlists transferred just fine.  However, my main playlist (largest) causes pyportify to crash with the following error:

Listening on http://0.0.0.0:3132
Please open your browser window to http://localhost:3132
Gathering tracks for playlist Starred (1753)
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "<string>", line 10, in main
  File "asyncio\base_events.py", line 295, in run_forever
  File "asyncio\base_events.py", line 1218, in _run_once
  File "selectors.py", line 314, in select
  File "selectors.py", line 305, in _select
ValueError: too many file descriptors in select()
server returned -1

I tried breaking up the playlist into two so that they were less than 1000 songs each (since Google has this restriction), but it results in the same error.

**Comment by pjssilva** [comment]
I have a similar problem. I have a big playlist with all the music saved in my Spotify account. When I try to transfer it I get many errors like this:

aiohttp.errors.ClientOSError: [Errno 24] Cannot connect to host mclients.googleapis.com:443 ssl:True [Can not connect to mclients.googleapis.com:443 [Too many open files]]

Maybe pyportify is trying to transfer too many information at once?

**Comment by rckclmbr** [comment]
This has actually been resolved in the repo itself.  You're correct -- there was no throttling to the service. I haven't made a release with this fix yet (at least for Windows).  Are you on OSX?  If so, you can give https://github.com/rckclmbr/pyportify/releases/download/v0.3.4/pyportify.dmg a try.

**Comment by pjssilva** [comment]
Hmm.... I am on linux and I installed it using pip.

I'll try to see if I can clone the repo itself and report back.

**Comment by rckclmbr** [comment]
This has been fixed for a while, thanks for reporting.
