### ISSUE TITLE
Playlist order lost during transfer

### ISSUE THREAD

**Issue by swishkin** [rckclmbr/pyportify#67]
pyportify successfully transferred 99% of my playlist, but along the way it lost the original order.

I'd love it if pyportify would recreate the playlist as closely to the original as possible.

Thanks!

Note: I used GPM Unlimited, but transferred from Spotify Free (so at least that path should work fine).

**Comment by roman-ku** [comment]
I need this badly.

That is not that hard to do, since the Spotify API includes a `added_at` attribute. This attribute is described as `The date and time the track was added.`. Now you just just have to find the tracks on Google Play in the same order as they were added to in Spotify.

**Comment by roman-ku** [comment]
Actually looking into this more, the Spotify API for the following: tracks in a playlist, playlists, and your saved songs, all actually return them in the correct order.

I think somewhere along the line pyportify uses a python data type which is not ordered.

**Comment by roman-ku** [comment]
Looking at issues of the parent project, I found: [https://github.com/mauimauer/portify/issues/5](https://github.com/mauimauer/portify/issues/5)

So maybe the random order is due to the async nature of adding the songs. I don't know if that's the problem, but that's a possibility.

**Comment by rckclmbr** [comment]
This should be fixed in 95baa37d3857b87978d4c52affab5735a90d9ffb -- it looks like `asyncio.wait()` doesn't return the futures in order, but the order they are first processed.  Switching to `asyncio.gather()` seemed to work fine.

Give [v0.3.6](https://github.com/rckclmbr/pyportify/releases/tag/v0.3.6) a try

**Comment by roman-ku** [comment]
I gave it a spin and it looks like it did the trick! Thank you.
