### ISSUE TITLE
Can't login with Gmail

### ISSUE THREAD

**Issue by electriceccentric** [rckclmbr/pyportify#70]
I have allowed less secure apps and tried through the browser and command line. Any ideas?

> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/aiohttp/server.py", line 266, in start
>     yield from self.handle_request(message, payload)
>   File "/usr/local/lib/python3.4/dist-packages/aiohttp/web.py", line 90, in handle_request
>     resp = yield from handler(request)
>   File "/usr/local/lib/python3.4/dist-packages/pyportify/app.py", line 43, in google_login
>     token = yield from g.login(email, password)
>   File "/usr/lib/python3.4/asyncio/coroutines.py", line 141, in coro
>     res = func(_args, *_kw)
>   File "/usr/local/lib/python3.4/dist-packages/pyportify/google.py", line 27, in login
>     res = gpsoauth.perform_master_login(username, password, android_id)
>   File "/usr/local/lib/python3.4/dist-packages/pyportify/gpsoauth/**init**.py", line 55, in perform_master_login
>     'EncryptedPasswd': google.signature(email, password, android_key_7_3_29),
>   File "/usr/local/lib/python3.4/dist-packages/pyportify/gpsoauth/google.py", line 49, in signature
>     message = (email + u'\x00' + password).encode('utf-8')
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by floraline** [comment]
Try using an [application-specific password](https://security.google.com/settings/security/apppasswords). You should not have to allow less secure apps to do this.

**Comment by ygurin** [comment]
@floraline You answer fixed the problem for me. Thanks.

**Comment by rckclmbr** [comment]
Updated readme to point to this
