### ISSUE TITLE
Breaks on large playlists (under 1000 songs)

### ISSUE THREAD

**Issue by dannyakakong** [rckclmbr/pyportify#72]
I successfully used PyPortify on my smaller playlists.

I read that Google Music only supports playlists with less than 1000 songs, so I created smaller playlists (to split up my large playlist) of just under 1000 songs (eg. 995).

PyPortify seems to choke on this, I've attached a partial command-line output showing this.

[stack.txt](https://github.com/rckclmbr/pyportify/files/419179/stack.txt)

Any help would be appreciated.

**Comment by rckclmbr** [comment]
This is happening because that version of pyportify executes all song requests at once with no throttling.  I have this fixed in the codebase but haven't released a new version yet.

**Comment by dannyakakong** [comment]
Thanks for the quick reply.

I've tried downloading and installing the latest repo version, but just get "failed to create process." so I'll wait for the next release.
