### ISSUE TITLE
Missing README.rst when running setup.py on Windows

### ISSUE THREAD

**Issue by dannyakakong** [rckclmbr/pyportify#73]
Downloaded zip file of project on GitHub:

C:\web\pyportify-master>python setup.py
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    with open(readme_rst) as readme:
IOError: [Errno 2] No such file or directory: 'README.rst'

**Comment by rckclmbr** [comment]
Fixed in ac1bb08caa86908bf872f23cd3d647a8bdb70eaf
