### ISSUE TITLE
Exception: Error: {'error': {'message': 'Insufficient client scope', 'status': 403}}

### ISSUE THREAD

**Issue by awanderingorill** [rckclmbr/pyportify#88]
<img width="603" alt="screen shot 2017-02-03 at 11 55 53 am" src="https://cloud.githubusercontent.com/assets/2730484/22600262/bff5a35e-ea07-11e6-80cf-68e24dfd1984.png">

Followed all instructions accurately and kept getting this error message after selecting to import all my playlists.

**Comment by rckclmbr** [comment]
I'm not sure which exactly permissions you need, but add more and try again.  I usually just check all boxes.
