### ISSUE TITLE
Importing songs containing '%' in the artist/song name result in an error.

### ISSUE THREAD

**Issue by Conorbro** [rckclmbr/pyportify#99]
Using binary search I managed to deduce that an artist in my rather large lo-fi hip hop playlist with the name **TOSHIKI HAYASHI(%C)** was causing the import to fail with the following stack trace:

<img width="396" alt="capture" src="https://cloud.githubusercontent.com/assets/5826063/25317369/5817f8f8-286f-11e7-83d2-da4401af43d6.PNG">

I suspect the issue is to do with the fact that the **'%'** character is present in his name.

Upon removing the artist from the playlist, it imported without issue. I then verified the problem by creating a test playlist containing only this artist which resulted in the same error.

**Comment by rckclmbr** [comment]
Good find

**Comment by rckclmbr** [comment]
This should be fixed in v0.3.14, give it a try and let me know.
